# Generated by Django 3.2.10 on 2023-10-31 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfirmation',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.basemodel')),
                ('verify_type', models.CharField(choices=[('via_phone', 'via_phone'), ('via_email', 'via_email')], max_length=31)),
            ],
            bases=('shared.basemodel',),
        ),
        migrations.AlterField(
            model_name='user',
            name='AUTH_TYPE',
            field=models.CharField(choices=[('via_email', 'via_email'), ('via_phone', 'via_phone')], max_length=31),
        ),
    ]
